### GENERAL SETTINGS ###

# Site settings
title: ABDOMINAIS
description: "Saiba como obter abdominais definidos. Só os melhores exercícios abdominais."
baseurl: "" #important: start with /
url: "http://abdominais.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--mais--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: http://www.facebook.com/abdominais
  - title: twitter
    url: http://www.twitter.com/abdominais
  - title: youtube
    url: https://www.youtube.com/user/abdominaiscom

about: Só os melhores exercícios abdominais
